---

- hosts: all
  become: true
  tasks:

  - name: Install apache2 and php support with cache update
    apt:
      name:
        - apache2
        -  libapache2-mod-php
      state: latest update_cache: yes

